version: '3.1'
services:
 media-server:
  env_file: ./.env
  image: ${IMAGE_PATH}:${VERSION}
  network_mode: host
  ports:
  - "1935:1935"
  volumes:
  - "${LOGS_DIR}/:/var/log/wowza/"
  restart: always
  container_name: media-server

 nginx:
  container_name: nginx
  image: nginx
  network_mode: host
  volumes:
  - ./nginx.conf:/etc/nginx/nginx.conf
  - "${LOGS_DIR_NGINX}/:/var/log/nginx/"
  restart: always